spring:
  profiles:
    active: dev
  application:
    name: spring-boot-admin-server1

server:
  port: 8000
  servlet:
    encoding:
      # 修改编码
      charset: UTF-8
      force: true
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

