spring:
  profiles:
    active: dev
  datasource:
    name: mysql1
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  servlet:
    encoding:
      # 修改编码
      charset: UTF-8
      force: true
      enabled: true

mybatis:
  # 映射文件位置
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Admin
    filter:
      create: All tasks

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
