spring:
  profiles:
    active: dev


# 配置swagger文档的访问路径，访问地址：http://127.0.0.1:8080/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html


server:
  servlet:
    encoding:
      # 修改编码
      charset: UTF-8
      force: true
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
