version: "3.9"
services:
  zookeeper:
    # 该镜像具体配置参考 https://github.com/bitnami/bitnami-docker-kafka/blob/master/README.md
    image: "bitnami/zookeeper:latest"
    hostname: zookeeper
    container_name: zookeeper
    privileged: true
    environment:
      # 匿名登录--必须开启
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
      - "8080:8080"
    volumes:
      - ./data/zookeeper:/bitnami/zookeeper
    networks:
      - net1

  kafka:
    # Web 管理界面 另外也可以用exporter+prometheus+grafana的方式来监控 https://github.com/danielqsj/kafka_exporter
    image: "bitnami/kafka:latest"
    hostname: kafka
    container_name: kafka
    privileged: true
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      # 虚拟机ip
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.20.130:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # 允许使用PLAINTEXT协议(镜像中默认为关闭,需要手动开启)
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 关闭自动创建 topic 功能
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # 全局消息过期时间 6 小时(测试时可以设置短一点)
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
      # 开启JMX监控
      - JMX_PORT=9999
    ports:
      - "9092:9092"
      - "9999:9999"
    volumes:
      - ./data/kafka:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - net1

  kafka_manager:
    image: "hlebalbau/kafka-manager:latest"
    hostname: kafka_manager
    container_name: kafka_manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    depends_on:
      - zookeeper
      - kafka
    networks:
      - net1

networks:
  net1:
    driver: bridge
