spring:
  application:
    name: seata-demo1
  profiles:
    active: dev

server:
  servlet:
    encoding:
      # 修改编码
      charset: UTF-8
      force: true
      enabled: true

seata:
  enabled: true
  # 事务组的名称，对应service.vgroupMapping.default_tx_group=xxx中配置的default_tx_group
  tx-service-group: default_tx_group
  # 配置事务组与集群的对应关系
  service:
    vgroup-mapping:
      # default_tx_group为事务组的名称，default为集群名称
      default_tx_group: default
    grouplist:
      # default为集群名称
      default: 127.0.0.1:8091
  registry:
    type: file
  config:
    type: file
