spring:
  profiles:
    active: dev
  datasource:
    name: mysql1
    type: com.zaxxer.hikari.HikariDataSource


mybatis:
  # 映射文件位置
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-location:  classpath:mybatis/mybatis-config.xml

