spring:
  profiles:
    active: dev
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
shiro:
  web:
    enabled: true
  loginUrl: /login
  unauthorizedUrl: /403
